-- Oto Burada - Database Schema
--
-- This file is now a placeholder. 
-- Please refer to the 'database' directory for the new structure:
--
-- database/schema.base.sql      : Foundation schema
-- database/migrations/*.sql     : Incremental changes
-- database/schema.snapshot.sql  : Full current state (Snapshot)
--
-- Link: database/schema.snapshot.sql
