export const listingSelect = `
id,
seller_id,
slug,
title,
category,
brand,
model,
year,
mileage,
fuel_type,
transmission,
price,
city,
district,
description,
whatsapp_phone,
vin,
license_plate,
car_trim,
tramer_amount,
damage_status_json,
fraud_score,
fraud_reason,
status,
featured,
featured_until,
urgent_until,
highlighted_until,
is_featured,
is_urgent,
frame_color,
gallery_priority,
small_photo_until,
homepage_showcase_until,
category_showcase_until,
top_rank_until,
detailed_search_showcase_until,
bold_frame_until,
market_price_index,
expert_inspection,
published_at,
bumped_at,
view_count,
version,
created_at,
updated_at,
listing_images (
  id,
  listing_id,
  storage_path,
  public_url,
  sort_order,
  is_cover,
  placeholder_blur
),
seller:profiles!inner!seller_id(id, full_name, city, avatar_url, role, user_type, business_name, business_logo_url, is_verified, is_banned, ban_reason, verified_business, verification_status, trust_score, business_slug, created_at, updated_at)
`;

export const legacyListingSelect = `
id,
seller_id,
slug,
title,
brand,
model,
year,
mileage,
fuel_type,
transmission,
price,
city,
district,
description,
whatsapp_phone,
status,
featured,
created_at,
updated_at,
market_price_index,
car_trim,
vin,
tramer_amount,
damage_status_json,
view_count,
version,
bumped_at,
featured_until,
urgent_until,
highlighted_until,
listing_images (
  id,
  listing_id,
  storage_path,
  public_url,
  sort_order,
  is_cover,
  placeholder_blur
),
seller:profiles!inner!seller_id(id, full_name, city, avatar_url, role, user_type, business_name, business_logo_url, is_verified, is_banned, ban_reason, verified_business, verification_status, trust_score, business_slug, created_at, updated_at)
`;

/**
 * OPTIMIZED select for marketplace list/grid display.
 * Excludes heavy fields like description, damage_status_json, etc.
 * Significant performance gain for LCP and memory usage.
 *
 * Performance note:
 * This select already includes JOINs for listing_images and profiles,
 * preventing N+1 queries. All related data is fetched in a single query.
 */
export const publicListingDetailSelect = `
id,
seller_id,
slug,
title,
category,
brand,
model,
year,
mileage,
fuel_type,
transmission,
price,
city,
district,
description,
whatsapp_phone,
car_trim,
tramer_amount,
damage_status_json,
status,
featured,
featured_until,
urgent_until,
highlighted_until,
is_featured,
is_urgent,
frame_color,
gallery_priority,
small_photo_until,
homepage_showcase_until,
category_showcase_until,
top_rank_until,
detailed_search_showcase_until,
bold_frame_until,
market_price_index,
expert_inspection,
published_at,
bumped_at,
view_count,
created_at,
updated_at,
listing_images (
  id,
  listing_id,
  storage_path,
  public_url,
  sort_order,
  is_cover,
  placeholder_blur
),
seller:profiles!inner!seller_id(id, full_name, city, avatar_url, role, user_type, business_name, business_logo_url, is_verified, is_banned, ban_reason, verified_business, verification_status, trust_score, business_slug, created_at, updated_at)
`;

/**
 * OPTIMIZED select for marketplace list/grid display.
 */
export const marketplaceListingSelect = `
id,
seller_id,
slug,
title,
category,
brand,
model,
year,
mileage,
fuel_type,
transmission,
price,
city,
district,
whatsapp_phone,
status,
featured,
featured_until,
urgent_until,
highlighted_until,
is_featured,
is_urgent,
frame_color,
gallery_priority,
small_photo_until,
homepage_showcase_until,
category_showcase_until,
top_rank_until,
detailed_search_showcase_until,
bold_frame_until,
market_price_index,
published_at,
bumped_at,
view_count,
created_at,
expert_inspection,
listing_images (
  id,
  listing_id,
  public_url,
  sort_order,
  is_cover,
  placeholder_blur
),
seller:profiles!inner!seller_id(id, full_name, avatar_url, role, user_type, business_name, is_verified, verification_status, business_slug)
`;

/**
 * Ultra-minimal select for listing cards in grid/list views.
 * Reduces network transfer and memory usage by ~60% vs marketplaceListingSelect.
 */
export const listingCardSelect = `
id,
slug,
title,
brand,
model,
year,
mileage,
fuel_type,
transmission,
price,
city,
status,
is_featured,
is_urgent,
frame_color,
market_price_index,
view_count,
expert_inspection,
listing_images!inner (
  public_url,
  is_cover,
  placeholder_blur
),
seller:profiles!inner!seller_id(id, full_name, is_verified, business_name, business_slug)
`;
